name: 6dylan6-jdpro-sync
on:
  schedule:
    - cron: "1 */3 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/6dylan6/jdpro.git"
          source_branch: "main"
          destination_branch: "w"
          github_token: ${{ secrets.PAT }}
